name: 📡 CricHD Playlist Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"   # প্রতি ১ ঘন্টায় run

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: 📥 Install Dependencies
        run: pip install requests

      - name: ▶️ Run Script
        run: python crichd_sm.py

      - name: 💾 Commit & Push Files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add crichd.m3u crichd_data.json
          git diff --cached --quiet || git commit -m "🔄 Auto update CricHD playlist & JSON"
          git push
